version: '3.4'

services:
  pdfview:
    image: pdfview
    build:
      context: src/presentation
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3000
    networks:
      - common
  pdffactory:
    image: pdffactory
    build:
      context: src/pdf-utilities
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5001:5001
    networks:
      - common
  teamchannelapi:
    image: teamchannelapi
    depends_on:
      - pdffactory
      - pdfview
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - 5000:5000
    networks:
      - common

networks:
  common:
    # Use a custom driver
    driver: bridge
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

